### ISSUE TITLE
Error in matrix.h

### ISSUE THREAD

**Issue by P705** [apryor6/splinterp#5]
Hi
I find mex.h and other libraries in matlab installation directory. But my program can't run because of different errors. The image of different errors attaches to you. 
How can i handle these errors?

Another basic question is about the mex.h.
The mex.h and other libraries were used for c++ code. that means the functions in matlab can be used in c++. that is right ?
![image](https://user-images.githubusercontent.com/57658660/75138895-9040be00-5700-11ea-9b9c-19cbbca0a0e4.png)

**Comment by apryor6** [comment]
These kinds of issues are usually related to the version of the installed C++ compiler. See the following link for more information:

https://www.mathworks.com/support/requirements/supported-compilers.html
